---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: create-bucket-service-account
  namespace: minio-tenant
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: create-bucket
  namespace: minio-tenant
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-secrets
  namespace: minio-tenant
subjects:
- kind: ServiceAccount
  name: create-bucket-service-account
  namespace: minio-tenant
roleRef:
  kind: Role
  name: create-bucket
  apiGroup: rbac.authorization.k8s.io


