apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
spec:
  podMonitorSelector:
    matchLabels:
      observability: local
  serviceAccountName: prometheus
  serviceMonitorSelector:
    matchLabels:
      observability: local
  resources:
    requests:
      memory: 400Mi
  enableAdminAPI: false